 version: 2
  jobs:
   one:
     build:
       docker:
         - image: circleci/ruby:2.4.1
       steps:
         - checkout
         - run: echo "A first hello"
         - run: sleep 25
   two:
     build:
       docker:
         - image: circleci/ruby:2.4.1
       steps:
         - checkout
         - run: echo "A more familiar hello"
         - run: sleep 15
   workflows:
   version: 2
   one_and_two:
     jobs:
       - one
       - two
